name: Reusable Build

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      registry:
        required: true
        type: string
      username:
        required: true
        type: string
    secrets:
      REGISTRY_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::960451805205:role/GitHubActionsRole
          aws-region: ap-southeast-1

      - name: Test AWS Access
        run: aws sts get-caller-identity

      - uses: docker/setup-buildx-action@v3

      - name: Login
        run: echo ${{ secrets.REGISTRY_TOKEN }} | docker login ${{ inputs.registry }} -u ${{ inputs.username }} --password-stdin

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ inputs.registry }}/${{ inputs.image-name }}:${{ github.sha }}
            ${{ inputs.registry }}/${{ inputs.image-name }}:latest
          cache-from: |
            type=registry,ref=${{ inputs.registry }}/${{ inputs.image-name }}:cache
          cache-to: |
            type=registry,ref=${{ inputs.registry }}/${{ inputs.image-name }}:cache,mode=max,image-manifest=true

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.34.2
        with:
          scan-type: "image"
          image-ref: ${{ inputs.registry }}/${{ inputs.image-name }}:latest
          format: "table"
          exit-code: 0
          ignore-unfixed: true
          severity: CRITICAL,HIGH
